### ISSUE TITLE
Command handler in Javascript?

### ISSUE THREAD

**Issue by daicaga** [clayallsopp/HybridKit-JS#1]
Hi @clayallsopp 

Your library is awesome with me. Thank you!

But I have an issue, please help me to know.
I run a command with name "my_command" in iOS Native code.
How I can catch this command to handle something in Javascript?

Best Regard,
Ga

**Comment by clayallsopp** [comment]
I don't think HybridKit has an opinion on this pattern - you can use typical `UIWebView` methods like `stringByEvaluatingJavaScriptFromString:` to invoke JS calls from Objective-C land

Hope that helps!

**Comment by daicaga** [comment]
OK, I got it, @clayallsopp 
Thanks!
